[notification]
num_messages = 3
max_body_length = 1000
split_long_messages = true
timezone = "Asia/Tokyo"
title_template = "🕐 {TIMESTAMP_TZ} - {GIT_REPO} ({GIT_BRANCH}) completed"
body_template = "Task completed at {TIMESTAMP_TZ}\nTimezone: {TIMEZONE}\nDate: {DATE}\nTime: {TIME}"

[pushbullet]
# Uses PUSHBULLET_TOKEN environment variable

[logging]
debug = true