name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      
      - name: Install dependencies
        run: |
          uv sync --dev
      
      - name: Run ruff format check
        run: |
          uv run ruff format --check .
      
      - name: Run ruff linter
        run: |
          uv run ruff check .
      
      - name: Run pyright type checking
        run: |
          uv run pyright claude_code_pushbullet_notify || true